### ISSUE TITLE
login window is hidden behind the Web3Connect provider select window

### ISSUE THREAD

**Issue by dkent600** [torusresearch/torus-embed#100]
**Describe the bug**
Your login window is hidden behind the Web3Connect provider select window.  Can't login.

**To Reproduce**
1. Go to https://alchemy-competition-rinkeby.herokuapp.com/
1. make sure 3rd-party cookies are enabled in the browser
1. Click on "Login" button
1. Select Torus
1. See screenshot.  As a result it is not possible to login.

**Expected behavior**
Your window should have a higher z-order to appear over the Web3Connect window

**Screenshots**
![image](https://user-images.githubusercontent.com/1821666/74085068-f9ef7580-4a3a-11ea-8db3-952591b2d69f.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome, Edge chromium
 - latest versions

**Smartphone (please complete the following information):**
 N/A -- repro case is on desktop

**Additional context**
None

**Comment by chaitanyapotti** [comment]
Hi.. can you specify the version of torus-embed you are using.?
We used the latest version and aren't able to reproduce the issue.

**Comment by dkent600** [comment]
I am calling `toggleModal()` on `Web3Connect.Core`.

@toruslabs/torus-embed version 0.2.14

**Comment by chaitanyapotti** [comment]
Hi, when i try locally or production, this seems to be the screen.
It would be of great help if you could help us track this down.

![web3connect](https://user-images.githubusercontent.com/1688380/74158632-5fb74980-4c55-11ea-881d-e2f921ff092a.png)

**Comment by dkent600** [comment]
ok, as a way to repro:  Try clicking on "Log In" in the upper-right at this url:

https://alchemy-addtoruswalletp-bdyara.herokuapp.com

**Comment by tetratorus** [comment]
There is something on your page with a higher z-index. 

Setting the toruswidget z-index to a higher value (10000000), resolved this issue.

Perhaps some imported javascript is setting an element with a particularly high z-index, if you fix that this issue should go away.

**Comment by dkent600** [comment]
> There is something on your page with a higher z-index.

Yeah, the Web3Connect modal.  That is the issue.

**Comment by jellegerbrandy** [comment]
Hey @tetratorus , you guys setting z-index lower then the web3connect modal  means that your modal is not usable with web3connect.  If this is true, it is a bug on your side which is very easy to fix, and this is currently blocking us from integrating torus with our dapp alchemy.daostack.io , and should be a problem for any app that uses web3connect and wants to integrate torus. So please reconsider opening this issue?

**Comment by chaitanyapotti** [comment]
Hello everyone,
I bumped up the z-index of torus. The issue should be resolved now.

**Comment by dkent600** [comment]
Closed, but no PR and no release?

**Comment by chaitanyapotti** [comment]
@dkent600 we put the css for the elements in torus-embed inside torus-website in a separate file 'widget.css' (because of this reason)
I updated the prod of torus-website with the css change directly.

**Comment by dkent600** [comment]
@chaitanyapotti 

torus-embed, within Alchemy (our dApp), is pulling "https://app.tor.us/v0.2.14/css/widget.css" which still exhibits the bug.

**Comment by chaitanyapotti** [comment]
Hey, @dkent600  please clear cache and hard reload stuff. It should work.

**Comment by dkent600** [comment]
@chaitanyapotti It really and truly isn't working despite clearing caches.

**Comment by dkent600** [comment]
Hi @chaitanyapotti, if you can let me know which line in the file you believe fixes this bug, I can confirm what is happening at our end, and determine why it is not working.

**Comment by orenyodfat** [comment]
> @dkent600 we put the css for the elements in torus-embed inside torus-website in a separate file 'widget.css' (because of this reason)
> I updated the prod of torus-website with the css change directly.

@chaitanyapotti are you referring to https://github.com/torusresearch/torus-website/pull/904 ? 
is there  https://app.tor.us/v1.1.0/css/widget.css ?
where we can see all your releases ?

**Comment by dkent600** [comment]
@chaitanyapotti @orenyodfat the 1.1.1 version doesn't work either.

Why? Because this:

```
#torusWidget {
  z-index: 999999;
  position: fixed;
}
```

needs to be this:

```
#torusWidget {
  z-index: 99999999;
  position: fixed;
}
```

**Comment by dkent600** [comment]
So the problem in the end was that our app was bumping up the z-index of the web3connect modal, causing it to appear over the torus popup.  I found a zindex for web3connect that makes everyone happy.  So this ticket is ok to be closed.
