### ISSUE TITLE
Unable to Access Torus from DefiSnap

### ISSUE THREAD

**Issue by elishatorus** [torusresearch/torus-embed#118]
**Describe the bug**
Unable to access Torus from DefiSnap despite changing the cookies settings.

**To Reproduce**
1. Go to https://www.defisnap.io/#/
2. Attempt to connect to Torus Wallet
3. Cookies Required modal will appear

**Expected behavior**
Expected to login directly after changing the cookies settings.

**Screenshots**
<img width="1792" alt="Screenshot 2020-03-10 at 4 03 28 PM" src="https://user-images.githubusercontent.com/51352241/76292042-60410f80-62e9-11ea-90d4-7a2f295fd883.png">

<img width="1792" alt="Screenshot 2020-03-10 at 4 02 44 PM" src="https://user-images.githubusercontent.com/51352241/76292080-7353df80-62e9-11ea-993b-e642d8570970.png">

**Desktop (please complete the following information):**
 - OS: iOS 10.15.2
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Comment by chaitanyapotti** [comment]
This is fixed and will be released along with the next version @elishatorus
