### ISSUE TITLE
error message running npm

### ISSUE THREAD

**Issue by dkent600** [torusresearch/torus-embed#142]
Running npm install on my project which contains torus-embed as a dependency, I get the following error message, and the npm command fails:

> npm ERR! git C:\Users\dkent\Documents\Projects\GitHub\DAOStack\alchemy\node_modules\@toruslabs\torus.js: Appears to be a git repo or submodule.
npm ERR! git     C:\Users\dkent\Documents\Projects\GitHub\DAOStack\alchemy\node_modules\@toruslabs\torus.js
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

 - OS: Windows
 - Version 10

npm v6.7.0

**Comment by chaitanyapotti** [comment]
This issue has been resolved. Please try again. It's recommended that you delete node_modules, yarn.lock or package-lock.json and do it
