### ISSUE TITLE
torus logo would look nicer with transparent background

### ISSUE THREAD

**Issue by dkent600** [torusresearch/torus-embed#143]
The torus logo used in Web3Modal would look nicer with a transparent background.  The other product icons all have transparency.  Only a problem while hovering over the card:

![image](https://user-images.githubusercontent.com/1821666/78377851-2b4d7300-759e-11ea-9d8e-292bfc2da59d.png)

**Comment by chaitanyapotti** [comment]
This needs to be transferred to web3modal. I'll raise a PR there with the updated image

**Comment by chaitanyapotti** [comment]
https://github.com/Web3Modal/web3modal/pull/139
