### ISSUE TITLE
[login modal] Login modal not updated to latest UI

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-embed#152]
Current <img width="469" alt="Screenshot 2020-04-30 at 9 46 11 AM" src="https://user-images.githubusercontent.com/53069682/80663848-b7808680-8ac7-11ea-87b6-fe7d485034fa.png">

Proposed
<img width="381" alt="Screenshot 2020-04-30 at 9 54 00 AM" src="https://user-images.githubusercontent.com/53069682/80664196-ab48f900-8ac8-11ea-86ab-0827c5801e04.png">

Have to also check if DApp wants the login to be labeled as "Your Google/FB Digital wallet

**Comment by chaitanyapotti** [comment]
Coming soon.!

**Comment by chaitanyapotti** [comment]
Closed by #165
