### ISSUE TITLE
ETH fee not valid whilst trying to make a DAI transfer on VUE

### ISSUE THREAD

**Issue by elishatorus** [torusresearch/torus-embed#156]
**Describe the bug**
Make a DAI transaction from Vue-embed. The ETH transaction fee shows up as NaN without the option of changing the fee.

**To Reproduce**
1. Go to vue embed.
2. Click Send DAI

**Expected behavior**
The option to choose the ETH Transaction fee should appear, allowing me to proceed with the transaction.

**Screenshots**
<img width="612" alt="Screenshot 2020-04-30 at 5 42 35 PM" src="https://user-images.githubusercontent.com/51352241/80696730-6c3b9780-8b0a-11ea-89a2-0af286f56d3b.png">

**Desktop (please complete the following information):**
 - OS: Mac PS
 - Browser: Chrome

**Comment by chaitanyapotti** [comment]
Fixed in this commit: 
https://github.com/torusresearch/torus-website/commit/87774d1975d61c07d91826309b1e2c484b7dc022
