### ISSUE TITLE
torus.getUserInfo() returns error `ObjectMultiplex - orphaned data for stream "user_info"`

### ISSUE THREAD

**Issue by miguelmota** [torusresearch/torus-embed#16]
Example to reproduce:

```html
<!DOCTYPE html>
<html lang="en-US">
<head>
  <meta charset="UTF-8">
  <title></title>
</head>
<body>
  <button id="login">login</button>
  <script src="bundle.js"></script>
</body>
</html>
```

```js
const Torus = require('@toruslabs/torus-embed').default

;(async () => {
  const torus = new Torus()

  await torus.init()

  const login = document.querySelector('#login')
  login.addEventListener('click', async event => {
    event.preventDefault()
    await torus.login()
  })
})();
```

After logging in, do `await torus.getUserInfo()` and instead of returning the user info it returns the error:

<img width="592" alt="Screen Shot 2019-08-12 at 3 29 04 PM" src="https://user-images.githubusercontent.com/168240/62903026-453bfc00-bd16-11e9-86bb-95a418b6f180.png">

The user is logged in and `torus.web3.eth.defaultAccount` returns the account address

Any thoughts on how to fetch the logged in user data such as email and name without getting the error?

Using version latest version 0.0.25 and latest version 76 of Chrome

Thanks!

**Comment by chaitanyapotti** [comment]
Please don't use 
```js
await torus.login()
```
Instead, use 
```js
await torus.ethereum.enable()
```

Please refer to the example provided [here](https://github.com/torusresearch/torus-embed/blob/master/examples/react-basic-app/src/helper.js#L13)

**Comment by chaitanyapotti** [comment]
#20 removes the confusion
