### ISSUE TITLE
[Recent Activity] Recent activity on widget is different from the one in transaction activity

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-embed#168]
<img width="1376" alt="Screenshot 2020-05-11 at 4 08 29 PM" src="https://user-images.githubusercontent.com/53069682/81539044-34eaa780-93a2-11ea-8ee4-f08aa702c7e0.png">
To make the recent activity on widget to be the one on activity page. 
Currently it is not the latest transaction

**Comment by carloslastresDev** [comment]
On the widget, I'm getting this
![image](https://user-images.githubusercontent.com/15041375/81540095-b989f580-93a3-11ea-9d90-6e6aac437e3b.png)

and on the app 
![image](https://user-images.githubusercontent.com/15041375/81540110-c0186d00-93a3-11ea-8798-c8eb07259649.png)

None of them is even nearby 0.0012 ETH
