### ISSUE TITLE
Method to logout?

### ISSUE THREAD

**Issue by miguelmota** [torusresearch/torus-embed#17]
Currently the user needs to click logout on the popup window to logout from the dapp. Is there a way to logout from google from within the dapp without closing the tab? Didn't see a logout method in the [documentation](https://docs.tor.us/developers/api-reference).

**Comment by chaitanyapotti** [comment]
Yes.

just call 
```js
torus.login(false)
```
to logout.

We will document this soon

**Comment by chaitanyapotti** [comment]
We'll be releasing a newer version of the package 0.0.26 before Aug 25<sup>th</sup> which would use private methods and remove the confusion.

In the new 0.0.26 API, you'll be able to use
```js
await torus.login()
```
to login and 
```js
await torus.logout()
```
to logout

**Comment by chaitanyapotti** [comment]
#20 Adds the new methods and a more streamlined api
