### ISSUE TITLE
[Approve KNC] Unknown/unreadable error message

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-embed#171]
<img width="501" alt="Screenshot 2020-05-11 at 5 27 28 PM" src="https://user-images.githubusercontent.com/53069682/81547779-e68fd580-93ae-11ea-876d-8f9524a1c18a.png">
To rephrase error message and translate it when necessary

**Comment by chaitanyapotti** [comment]
This error is from infura. (ethereum blockchain sends this error).
We just show it as is.! Ideally, in production apps, this error won't show up. I created some failing tx's in demo app because of which this error is shown.
