### ISSUE TITLE
Disable verbose console logs

### ISSUE THREAD

**Issue by miguelmota** [torusresearch/torus-embed#18]
The embedded torus iframe is emitting verbose logs into our dapp. Is there a way to disable the logging?

<img width="703" alt="Screen Shot 2019-08-12 at 5 39 14 PM" src="https://user-images.githubusercontent.com/168240/62907479-41b17080-bd28-11e9-9c3b-35ad9a3b1df8.png">

**Comment by chaitanyapotti** [comment]
We'll be releasing a newer version of the package 0.0.26 before Aug 25<sup>th</sup> which has an option to enable/disable logging and it is disabled by default

In the new 0.0.26 API, you'll be able to use
```js
await torus.login('production', true)
```
to enable logs

**Comment by chaitanyapotti** [comment]
#20 has the required logging api
