### ISSUE TITLE
Display hex or more human readable message on sign confirm popup

### ISSUE THREAD

**Issue by miguelmota** [torusresearch/torus-embed#19]
Right now it's displaying broken utf8 characters. An improvement would be to display hex like metamask

<img width="497" alt="Screen Shot 2019-08-12 at 5 46 20 PM" src="https://user-images.githubusercontent.com/168240/62907647-1f6c2280-bd29-11e9-8650-d8c822b5cd72.png">

**Comment by chaitanyapotti** [comment]
Can you please log the web3 request made to show this popup?

**Comment by miguelmota** [comment]
@chaitanyapotti here's the web3 call that triggers the popup:

```js
const msg = '0x9ef3dfe3973da969ea15f33004f77669b73ed912b255d14dbbe803352499adb0'
torus.web3.personal.sign(msg, torus.web3.eth.defaultAccount, async (err, sig) => {
      console.log(err, sig)
})
```

**Comment by chaitanyapotti** [comment]
Fixed
