### ISSUE TITLE
torus.getVerifier();

### ISSUE THREAD

**Issue by Nokhal** [torusresearch/torus-embed#196]
**Is your feature request related to a problem? Please describe.**
Currently, in order to avoid users having to select their verifier every ethereum.enable call, developers can call torus.login({verifier:"google"}). However, in order to get what their verifier is, platforms need to call "getUserInfo" which also expose details like their private email, which they might not want to do nor is necessary for the platform UX.

**Describe the solution you'd like**
torus.getVerifier() => returns string verifier so that torus.login({verifier:"google"}) can be called without exposing personal information to the integrating platform.

**Describe alternatives you've considered**

getUserInfo works but is too "rich" in data and i'd rather not know personal data of user I have not explicitly asked for from the user directly.

**Additional context**
Platforms that never collect personal data don't have to worry about GDPR.

**Comment by chaitanyapotti** [comment]
`torus.currentVerifier` gives you the desired result
