### ISSUE TITLE
Torus UI is breaking

### ISSUE THREAD

**Issue by superdev1994** [torusresearch/torus-embed#200]
I am using Typescript 3.9.4 and my app is CRA project.

```
    const torus = new Torus({});
    await torus.init({});
    await torus.login({});
```

because I refresh the page, it will happen again. I think that's why I can see this screen.

![image](https://user-images.githubusercontent.com/52289096/85413557-cd3a8700-b51f-11ea-9cff-77e4f47fe9ae.png)

![image](https://user-images.githubusercontent.com/52289096/85413581-d62b5880-b51f-11ea-9bf9-7f753b571665.png)

@chaitanyapotti explained that we can use `sessionStorage` to check if user logged in or not.
but I need to get Torus object or `torus.provider` (because I am only using torus.provider like a normal ethereum object)

I am trying to store the whole object into storage. xD it does not work. 

And I don't know why I am getting this error.

![image](https://user-images.githubusercontent.com/52289096/85414021-6ff30580-b520-11ea-89ab-74a8847aee4c.png)

The last error has occurred when I tried to `JSON.stringfy(torus.provider)`

**Comment by chaitanyapotti** [comment]
You can't stringify torus.provider (it has proxy objects - we follow EIP 1193 spec).

Regarding the UI errors, which version of torus are you using? (please update to the latest v1.5.4. It has a bunch of UI fixes)

**Comment by superdev1994** [comment]
@chaitanyapotti I updated from version 1.5.3 to 1.5.4 and UI bugs disappeared. But I am still getting errors.

![image](https://user-images.githubusercontent.com/52289096/85568018-2ff65600-b5e6-11ea-990c-88833cee70d7.png)

**Comment by chaitanyapotti** [comment]
Those errors are acceptable. Sometimes, a node might not be reachable which may show logs. But, due to the threshold assumptions (that only 7/9 nodes need to be operational), you still get back your key.
Please ignore them for now
