### ISSUE TITLE
Global Torus object

### ISSUE THREAD

**Issue by superdev1994** [torusresearch/torus-embed#201]
Torus has advantages. It provides us a great way to use Ethereum.
Metamask is cold wallet but it needs extension but because it is extension, it is easy to make a dApp using Metamask.

They provide us `window.web3`, `window.ethereum `and we can check if Metamask is installed or action needed or so so.
Why can't torus?

After refreshing window, torus stays logged in. This is awesome. But I want to get Torus in my code and want to make transactions. Teach me if I don't well about Torus. :)

**Comment by chaitanyapotti** [comment]
Hey, thanks for opening an issue.
We have a lot of examples [here](https://github.com/torusresearch/torus-embed/tree/master/examples) and documentation [here](https://docs.tor.us/).
Please go through them. if you have any questions, please reach out to us on telegram. Links are available [here](https://tor.us/)
