### ISSUE TITLE
Chain with ID 5 not supported

### ISSUE THREAD

**Issue by VoroshilovMax** [torusresearch/torus-embed#208]
After initialization Torus on Angular 9

```
import Web3 from 'web3'
import Torus from '@toruslabs/torus-embed'

const web3Obj = {
    web3: new Web3(),
    torus: new Torus({}),
    setWeb3(provider) {
        let web3Instance = new Web3(provider)
        web3Obj.web3 = web3Instance
    },
    async initialize() {
        await web3Obj.torus.init({
            showTorusButton: true,
            buildEnv: 'production',
            network: {
                host: 'goerli',
                chainId: 5
            }
        })
        await web3Obj.torus.login({})
        web3Obj.setWeb3(web3Obj.torus.provider)
    }
}

export default web3Obj
```
I want to interact with the smart contract stored on the Goerli network. For this I use 

```
let web3 = new Web3(web3Obj.web3.currentProvider)
let contract = new web3.eth.Contract(abi, contractAdrress)
let sendEther = await contract.methods.setEther().send({from: userAddress, value: value});
```
I always get an error that Chain with ID 5 not supported. With Metamask everything works correctly! How I can solve this problem? Any help very appreciated!

**Comment by chaitanyapotti** [comment]
The issue is due to incorrect chain id configuration in ethereumjs-common. I already raised an [issue](https://github.com/ethereumjs/ethereumjs-vm/issues/790) there and we are waiting for them to release.

**Comment by VoroshilovMax** [comment]
Hello, @chaitanyapotti I saw that ethereumjs-vm updated package. Will wallet work on the Goerli network now?

**Comment by chaitanyapotti** [comment]
Yes. We'll be releasing a new version by the end of this week
