### ISSUE TITLE
Not working on brave browser - error "Uncaught DOMException: Failed to read the 'localStorage'"

### ISSUE THREAD

**Issue by miguelmota** [torusresearch/torus-embed#22]
<img width="647" alt="Screen Shot 2019-08-13 at 10 21 06 PM" src="https://user-images.githubusercontent.com/168240/62996225-bcf24f80-be18-11e9-9bc4-d9049d378cf2.png">

The widget is not working with the brave shield enabled. Used brave Version 0.67 

The same code in [this issue](https://github.com/torusresearch/torus-embed/issues/16) was used if you want to reproduce the issue

**Comment by miguelmota** [comment]
Upon further inspection, the issue occurs when 3rd party cookies are blocked <img width="684" alt="Screen Shot 2019-08-13 at 10 30 15 PM" src="https://user-images.githubusercontent.com/168240/62996643-46eee800-be1a-11e9-8222-59ff975057fc.png">

An improvement would be to catch the error and gracefully handle it

**Comment by chaitanyapotti** [comment]
Handled

**Comment by miguelmota** [comment]
@chaitanyapotti the error is still happening with latest torus version 0.0.26 on Brave

![3vr6zyE9jl](https://user-images.githubusercontent.com/168240/63118928-c502da00-bf53-11e9-9dc3-512bcb822ff0.gif)

**Comment by chaitanyapotti** [comment]
Looks like a web3 issue. 
This [PR](https://github.com/ethereum/web3.js/pull/3031) merge would resolve it

**Comment by chaitanyapotti** [comment]
Looks like the PR is merged. 
Awaiting web3 1.2.1 release

**Comment by chaitanyapotti** [comment]
Released v0.2.0 which fixes this
