### ISSUE TITLE
Torus provider doesnt disconnect upon logout

### ISSUE THREAD

**Issue by zeroguz** [torusresearch/torus-embed#235]
**Describe the bug**
Torus provider doesnt disconnect upon logout

**To Reproduce**
  - connect to torus via torus-embed
  - logout via the popup torus website
  - provider is still connected but provides no more addresses,...

**Expected behavior**
  - provider should disconnect and call the disconnect handler

**Comment by chaitanyapotti** [comment]
Unlike metamask, torus provider still maintains a connection to the dapp even if the user logs out. (He can login again).
Hence, we don't emit disconnect
