### ISSUE TITLE
export es modules

### ISSUE THREAD

**Issue by wighawag** [torusresearch/torus-embed#239]
**Is your feature request related to a problem? Please describe.**
Currently torus does not export an es module. it only export to common js and UMD.

**Describe the solution you'd like**
For modern tooling (including tree shaking) it would be great to have es module. Some tooling do not even support non-es modules.

**Describe alternatives you've considered**
For my app, I have to use the umd module and load it separatly. I cannot benefit from code splitting automatically

**Comment by chaitanyapotti** [comment]
Currently, we had a lot of users complain about issues with polyfilling (non-webpack users) stream,buffer etc.
hence, we use webpack to bundle + polyfill even for cjs build.

We'll be exporting es modules along with webpack 5.

**Comment by chaitanyapotti** [comment]
Done with the latest release v1.14.0
