### ISSUE TITLE
API Reference link in the Readme needs to be updated

### ISSUE THREAD

**Issue by ayushgupta0610** [torusresearch/torus-embed#241]
**Describe the bug**
In the Readme file, the API reference link provided is broken (https://docs.tor.us/api-reference)

**To Reproduce**
1. Go to 'https://github.com/torusresearch/torus-embed'
2. Under the Introduction tab, 3rd line, the reference API link is provided
3. Clicking on that link points to 'Page Not Found' page

**Expected behavior**
It should navigate to the [api-reference](https://docs.tor.us/torus-wallet/api-reference) for the torus wallet

**Screenshots**
![image](https://user-images.githubusercontent.com/7221434/93014551-a5633880-f5cf-11ea-9587-bdec40631053.png)

**Comment by chaitanyapotti** [comment]
This is fixed now. Thanks
