### ISSUE TITLE
Not working on Safari - error "TypeError: undefined is not an object (evaluating 'r["a"].dispatch')"

### ISSUE THREAD

**Issue by miguelmota** [torusresearch/torus-embed#25]
<img width="739" alt="Screen Shot 2019-08-17 at 5 41 57 PM" src="https://user-images.githubusercontent.com/168240/63218758-7a7d8b00-c116-11e9-8f72-e91ef82849b5.png">

Happens on load. Tested using version torus-embed 0.0.26 on Safari 12.1 

The same code in [this issue](https://github.com/torusresearch/torus-embed/issues/16) was used if you want to reproduce the issue

**Comment by chaitanyapotti** [comment]
Looks like 
We use broadcast-channel (github)[https://github.com/pubkey/broadcast-channel] for communication b/w iframe(torus-website) and torus-embed
Safari doesn't like indexedDB from iframes - which the library is attempting to do
I'll modify our channels to only use localStorage and not idb in case of Safari

Thanks for pointing this out

**Comment by chaitanyapotti** [comment]
This [PR](https://github.com/torusresearch/torus-website/pull/384) which i opened should fix this issue

**Comment by chaitanyapotti** [comment]
PR merged to develop. Fixed. Will be released on torus-website v0.0.22

**Comment by miguelmota** [comment]
@chaitanyapotti do you have an ETA for when the site with the fix will be deployed?

**Comment by chaitanyapotti** [comment]
I'm just waiting for https://github.com/ethereum/web3.js/pull/3031 to be merged and released

**Comment by chaitanyapotti** [comment]
Released this

**Comment by miguelmota** [comment]
🎉
