### ISSUE TITLE
WebpackError: ReferenceError: btoa is not defined

### ISSUE THREAD

**Issue by aminlatifi** [torusresearch/torus-embed#255]
**Describe the bug**
Gatsby build process throws error when torus-embed library is added.

**To Reproduce**
1. Get this code which is using torus-embed library:
https://github.com/Giveth/giveth-2/tree/f_123_standard_torus_wallet
2. Install dependencies: `npm i`
3. Run build command: `npm run build`

**Desktop (please complete the following information):**
 - OS: macOS and Linux
 - Version 1.8.5
 - Node: 12

**Comment by chaitanyapotti** [comment]
Torus is a frontend only library.
If you're using it with SSR, please mark it as client side plugin (https://github.com/torusresearch/torus-embed#tips-for-nuxt)

**Comment by aminlatifi** [comment]
@chaitanyapotti Thanks
