### ISSUE TITLE
yarn add @toruslabs/torus-embed replaces the existing web3@1.3.0 to web3@0.20.7

### ISSUE THREAD

**Issue by kombos** [torusresearch/torus-embed#258]
I tried installing the @toruslabs/torus-embed yarn package and it downgraded the existing web3@1.3.0 to web3@0.20.7. This is causing problems in my web3modal package from functioning properly. Any way this can be rectified without monkey-patching with latest web3 version everytime torus_embed package is installed?

**Comment by chaitanyapotti** [comment]
Can you provide a minimal reproducible repo where we can test this.?
This shouldn't occur for any reason tbh.! @kombos

**Comment by kombos** [comment]
This is a simple reproduction - first install @drizzle/store package using yarn add. This will install web3@1.3.0 also in node_modules. Now try to install @toruslabs/torus_embed, and check the package.json of web3 package. Now the versions shows as 0.20.7

**Comment by chaitanyapotti** [comment]
This isn't an issue with our package but with the way yarn resolves dependencies.
This doesn't occur when used with npm. 
Quick fix is to specify the web3 version to be used in package.json 

![image](https://user-images.githubusercontent.com/1688380/96674864-3df19300-139c-11eb-9330-523c368a8e5b.png)
This will resolve the issue with yarn replacing web3

We are also not going to bundle web3 with torus-embed in next release to coincide with similar announcement from Metamask
