### ISSUE TITLE
Network select at initialization

### ISSUE THREAD

**Issue by Amxx** [torusresearch/torus-embed#26]
Right now, if I want my app to connect to goerli, I must do:

	const torus = new Torus.default();
	torus.init()
	.then(() => {
		torus.setProvider(config.provider.network);
		...
	});

which prompts a popup asking the user if he accepts this change. Would it be possible to set the network during the initialisation? This would smooth the app launch, while not really being a security issue.

**Comment by tetratorus** [comment]
Unfortunately that would lead to dapps being able to change network for the user without the user's permission. 

If the user is already on Goerli, he wont be prompted with a popup confirmation, so this only happens once.

**Comment by Amxx** [comment]
When a user arrives on the app for the first time and login, he isn't already on any blockchain. Right now he logs into mainnet by default, then you can prompt it to change network. How would logging by defaut on another network be a security issue? He is already going the logging, its just asking him to logging to a specific chain. Then if the app does `setProvider` then sure, we should ask the user

**Comment by Amxx** [comment]
For example, Portis SDK's does:

```
const portis = new Portis(config._protis.appId, config.provider.network);
portis.enable().then(() => {
    ...
});
```

which allows selecting the chain at launch. I don't see how that could be a security issue

**Comment by miguelmota** [comment]
Setting a default provider would be good!

In addition to Portis, Fortmatic also allows the developer to set the network:

```js
const fm = new Fortmatic('api key', 'kovan')
window.web3 = new Web3(fm.getProvider())
```

**Comment by bwheeler96** [comment]
I'm in favor of this

**Comment by chaitanyapotti** [comment]
After receiving feedback from multiple parties, we are gonna implement this feature in 0.0.29 version which will be released before Oct 8<sup>th<sup>.

**Comment by chaitanyapotti** [comment]
Closing this since it's merged
