### ISSUE TITLE
No way to determine if torus has initialized

### ISSUE THREAD

**Issue by bwheeler96** [torusresearch/torus-embed#28]
Upon calling `torus.init()` there is no way to tell if the initialization is complete. `isLoggedIn` is set to `false` at page load, and will continue to be false unless the user is signed in, but even if the user is signed in, `isSignedIn` will not necessarily be `true` immediately after calling `torus.init()`

This leads to the inability of developers to intelligently direct users to a login/default screen without having to do weird things in our code (timeouts, heuristics, etc)

**Comment by chaitanyapotti** [comment]
`.init()` returns a promise. You can await it.

**Comment by bwheeler96** [comment]
@chaitanyapotti 

```
torus.init()
.then(() => console.log(torus.isLoggedIn))

// => false
```

try that code snippet out, it doesn't work as expected

**Comment by chaitanyapotti** [comment]
`.init()` doesn't log you in. It just initializes the torus client (does integrity checks and creates the iframe)
`.login()` logs pops open the google login and logs you in.
`isLoggedIn` is updated when the google login is complete.

Please refer to the example [here](https://github.com/torusresearch/torus-embed/blob/master/examples/vue-app/src/App.vue#L25)

**Comment by bwheeler96** [comment]
@chaitanyapotti What if the user was logged in before the page loaded? I have found that `isLoggedIn` does not persist across window reloads even after init is called. Is this desired behavior?

**Comment by chaitanyapotti** [comment]
You can call the `.login()` again. If the user is already logged in, it will just pass through and won't popup the google window.
Optionally,
Please refer to this [example](https://github.com/torusresearch/torus-embed/tree/master/examples/react-basic-app/src) where we use a [sessionStorage variable](https://github.com/torusresearch/torus-embed/blob/master/examples/react-basic-app/src/helper.js#L9) to track if the user is logged in or not.
Use [rehydration](https://github.com/torusresearch/torus-embed/blob/master/examples/react-basic-app/src/App.js#L11)

**Comment by chaitanyapotti** [comment]
I think this can be closed now now that i've provided enough detail + explanation

**Comment by superdev1994** [comment]
@chaitanyapotti I called `.login()` and it breaks torus. 
![image](https://user-images.githubusercontent.com/52289096/85409263-741c2480-b51a-11ea-93ce-75f060fb1645.png)

**Comment by superdev1994** [comment]
another bug

![image](https://user-images.githubusercontent.com/52289096/85410744-4e901a80-b51c-11ea-9fb6-5573ae48449d.png)

**Comment by chaitanyapotti** [comment]
Can you raise a separate issue for this.? @superdev1994

**Comment by superdev1994** [comment]
@chaitanyapotti I created new issues
