### ISSUE TITLE
Unable to sign a raw transaction using TORUS?

### ISSUE THREAD

**Issue by imdanishsaber** [torusresearch/torus-embed#309]
**Describe the bug**

I am using TORUS wallet to make transactions over Quorum network. The requirement is to sign a raw transaction without broadcasting over network. TORUS does not allow to sign a transaction. Is there any way to sign a raw transaction with TORUS wallet?

**Expected behavior**
It should allow to sign a raw transaction.

**Screenshots**
Error logs:
![photo_2021-04-02_14-43-06](https://user-images.githubusercontent.com/70540320/113409904-a7ee7980-93cb-11eb-9990-6c96fd4124ef.jpg)

**Additional context**
Code Snippet:
`
                const rawTransaction = {
                  nonce: nonce,
                  gasLimit: gasLimit,
                  gasPrice: gasPrice,
                  from: this.publicAddress,
                  to: this.receiver.account,
                  value: 1,
                  data: data,
                };
                this.web3.eth.signTransaction(rawTransaction, this.publicAddress).then((signedTx) => {
                  console.log(signedTx);
              })
              .catch(console.log);
`

**Comment by chaitanyapotti** [comment]
Added documentation for this
