### ISSUE TITLE
loginConfig is not working for some of typeOfLogin

### ISSUE THREAD

**Issue by gnujoow** [torusresearch/torus-embed#340]
**Describe the bug**

Some of typeOfLogin is not effected by loginConfig

I wanted to show one of typOfLogin. so i initate torus with `enabledVerifiers` option and i worked well but this option is deprecated and there are only limited types can be disabled by this option. so I tried `loginConfig` but it didnt go well.
 

**To Reproduce**Steps to reproduce the behavior:
I initiate torus wallet with following option
```js
...
loginConfig: {
  'reddit': {
    name: '',
    typeOfLogin: 'reddit',
    showOnModal: false,
  },
  'twitch': {
    name: '',
    typeOfLogin: 'twitch',
    showOnModal: false,
  },
  'apple': {
    name: '',
    typeOfLogin: 'apple',
    showOnModal: false,
  },
  'github': {
    name: '',
    typeOfLogin: 'github',
    showOnModal: false,
  },
  'linkedin': {
    name: '',
    typeOfLogin: 'linkedin',
    showOnModal: false,
  },
  'twitter': {
    name: '',
    typeOfLogin: 'twitter',
    showOnModal: false,
  },
  'weibo': {
    name: '',
    typeOfLogin: 'weibo',
    showOnModal: false,
  },
  'line': {
    name: '',
    typeOfLogin: 'line',
    showOnModal: false,
  },
  'email-password': {
    name: '',
    typeOfLogin: 'email-password',
    showOnModal: false,
  },
},
...
```

**Expected behavior**
`twitch`, `apple`, `github`, `linkedin`, `twitter`, `weibo`, `line`, `email-password` are not shown on modal. with this above configuration only **reddit**  is not shown on modal.

**Screenshots**

![스크린샷 2021-06-24 오후 9 24 24](https://user-images.githubusercontent.com/10865414/123263183-a8626080-d533-11eb-9197-cd31a5f7826e.png)

**Desktop (please complete the following information):**
 - Device: 2020 m1 macbook pro
 - OS: osx bigsur 11.2.2
 - Browser: chrome v91.0.4472.106(arm64)
 - Version: v91.0.4472.106(arm64)
 
**Additional context**

I think typeoflogin in `VerifierStatus`(google, reddit, facebook, twitch, discord) are only effected by `loginConfig`

**Comment by himanshuchawla009** [comment]
Verifier should be a valid verifier name  (ie any one of default torus verifiers given here [here](https://github.com/torusresearch/torus-website/blob/develop/.env.production) or you can deploy your dapp scoped verifier from [developer dashboard ](https://developer.tor.us/) from custom auth section . 

For ex: it should be `torus-auth0-twitter` which is default torus verifier instead of `twitter`

You can find more information here:-

https://docs.tor.us/wallet/api-reference/class#loginconfig

**Comment by gnujoow** [comment]
@himanshuchawla009 thanks for your reply ;)
