### ISSUE TITLE
TypeError: Torus is not a constructor

### ISSUE THREAD

**Issue by vorcigernix** [torusresearch/torus-embed#351]
**Describe the bug**
Cannot initialize new Torus instance

**To Reproduce**
See [gist](https://gist.github.com/vorcigernix/a24881a40d5314f93c08131959351bd4)

**Expected behavior**
Torus object will work [as described](https://docs.tor.us/integration-builder/?b=wallet&chain=Ethereum&lang=React)

**Additional context**
This is probably Next/SSR related issue. Given how the technology works and documentation on both sides I think that the syntax in gist is correct and should work.

**Comment by chaitanyapotti** [comment]
We have a Next.Js example which shows how to do this:
https://github.com/torusresearch/torus-embed/blob/develop/examples/next-app/pages/index.tsx
