### ISSUE TITLE
Unable to use signTypedData on kovan

### ISSUE THREAD

**Issue by drortirosh** [torusresearch/torus-embed#371]
I have a web application that attempt o call signTypedData.
it works well to rinkeby, but on kovan I get an error:
`Provided chainId "42" must match the active chainId "66"`

Our application doesn't have any chainId hard-coded, only returned value from the provider itself.

The only cause of such a problem I can think of is that the decimal chainId (42) is taken as if it was a hex value,
 since `0x42 == 66` ...
It causes no problem with lower chainId like mainnet (1), rinkeby (3), ropsten(4)

**Comment by chaitanyapotti** [comment]
This has been fixed in the latest release
