### ISSUE TITLE
Feat: bundle without requiring babel as a peer dep

### ISSUE THREAD

**Issue by sambacha** [torusresearch/torus-embed#380]
**Is your feature request related to a problem? Please describe.**

Torus shouldn't need to be bundled with babel as a peer dependency

**Describe the solution you'd like**

Provide transpiled output artifacts or bundle process 

**Describe alternatives you've considered**

Removing Torus from supported applications 

**Additional context**

This causes unnecessary bloat for downstream apps wanting to support your wallet

**Comment by chaitanyapotti** [comment]
You can use the umd build/ script tag directly.
@babel/runtime is a standard way of bundling packages so that we don't polyfill extra content.

**Comment by sambacha** [comment]
I think you mis understand me, its easier to not include torus than to use a UMD build. The entire reason I created this issue is because the size of torus is actually a significant performance degradation for end users. 

Here is an example: instead of using a 1:1 fork of metamasks safe event emitter, why not just use that? that way you are not forcing consumers of your application to duplicate the exact same functionality twice thus increasing the total application size needlessly ?
