### ISSUE TITLE
Edit campaign functionality not working

### ISSUE THREAD

**Issue by namrataborole** [torusresearch/torus-embed#397]
Description:
Edit campaign functionality not working for a valid campaign id. It gives error message  its returning {"message":"Not Found"}

1. Go to 'postman'  and select the request to Edit campaign.
2. Enter a valid campaign id in the request and update the description.
3. Click on the Send button
3. Scroll down to Response
4. See error: {"message":"Not Found"}

Expected behavior:
On click of send, request should be processed and campaign should be updated.

**Comment by chaitanyapotti** [comment]
Not related to this repo
