### ISSUE TITLE
Ability to launch Torus Wallet with a key pair

### ISSUE THREAD

**Issue by apm-labs** [torusresearch/torus-embed#415]
**Is your feature request related to a problem? Please describe.**

I am using the Torus CustomAuth with my Firebase Auth app following the example put together here and everything works great:
https://github.com/torusresearch/CustomAuth/tree/master/examples/firebase-example

However, I'd like to launch the Torus Wallet with the public/private key acquired from CustomAuth's getTorusKey method without going through another login process with the Torus Wallet. That does not seem to be supported today.

I think this is an important use case for web2/3 apps that use external login solutions (such as Firebase) but still want to take advantage of the Torus Wallet.

**Comment by himanshuchawla009** [comment]
@apm-labs this feature is live now. 

https://github.com/torusresearch/torus-embed/blob/2a90698232412d7e3a3849d6f399a9dda6ce8c0d/src/embed.ts#L533

`loginWithPrivateKey` can be used to pass any ethereum (secp251k) private key along with user info. We will soon add documentation for it.

**Comment by himanshuchawla009** [comment]
closing it , feel free to open other issue if you face any hurdle while using this feature. Thanks.
