### ISSUE TITLE
ReferenceError: window is not defined (again)

### ISSUE THREAD

**Issue by reinhart1010** [torusresearch/torus-embed#416]
I currently face the exact same error as in #359 and #339 when importing `torus-embed` inside a Next.js application. Maybe another regression?

Package version: 1.20.3

**Comment by sakulstra** [comment]
Facing this issue as well

**Comment by ptrf** [comment]
Next.js performs server side rendering, which produces this error. Take a look at the [Next.js example in this repository](https://github.com/torusresearch/torus-embed/tree/develop/examples/next-app)

Specifically, [these lines](https://github.com/torusresearch/torus-embed/blob/develop/examples/next-app/pages/index.tsx#L48-L50) show how to perform dynamic import and initialization:

```
  useEffect(()=>{
    const initialize = async () => {
      const torus = (await import("@toruslabs/torus-embed")).default;
      web3Obj.torus = new torus({});
      const torusEnv = sessionStorage.getItem('pageUsingTorus');
      if (torusEnv) {
        login();
      }
    }
    initialize();
  }, [])
```
