### ISSUE TITLE
400 Bad request from google when trying to signin while Whitelabel is supplied to Torus.init() 

### ISSUE THREAD

**Issue by Wie-CBD** [torusresearch/torus-embed#450]
**Describe the bug**

This ran perfectly : 
```
Torus.init({
    "network": {
        "host": "goerli"
    },
    "showTorusButton": false,
    "buildEnv": "testing",
    "enableLogging": true,
    "whiteLabel": {
        "theme": {
            "isDark": true,
            "colors": {
                "torusBrand1": "#27b18a"
            }
        }
    }
})
```

And the Torus modal pops up as expected. However, when trying to login with google, it returns this error : 

![image](https://user-images.githubusercontent.com/30994905/167571093-4b056cb3-6d70-47c9-88a9-319df6076132.png)

**To Reproduce**
1. run `torus.init` with these parameters : 
```
{
    "network": {
        "host": "goerli"
    },
    "showTorusButton": false,
    "buildEnv": "testing",
    "enableLogging": true,
    "whiteLabel": {
        "theme": {
            "isDark": true,
            "colors": {
                "torusBrand1": "#27b18a"
            }
        }
    }
}
``` 
2. Initialize torus login 
3. Choose login with google
4. It'll return `400 bad request` error

**Expected behavior**
Login with google works as expected with whitelabel params supplied

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave browser and Google Chrome

**Smartphone (please complete the following information):**
Not tested on smartphone

**Additional context**
Was testing on Goerli

**Comment by chaitanyapotti** [comment]
Unable to reproduce this.
can you share a minimal reproducible example?

**Comment by Wie-CBD** [comment]
@chaitanyapotti I was able to reproduce this by assigning an imported `.svg` file to `logoDark` or `logoWhite` - something like this : 


```
import SVGDark from '../asset/svg-dark.svg'
import SVGLight from '../asset/svg-light.svg'

const TORUS_INIT_PARAMS = {
  network: {
    host: CURRENT_NETWORK.network,
  },
  showTorusButton: false,
  buildEnv:  'testing' ,
  enableLogging: true,
  whiteLabel: {
    theme: {
      isDark: true,
      colors: {
        torusBrand1: '#27b18a',
      },
    },
    logoDark: SVGDark,
    logoLight: SVGLight,
    topupHide: false,
    featuredBillboardHide: false,
    disclaimerHide: true,
    defaultLanguage: 'en',
  },
}

```
