### ISSUE TITLE
Option to enable uxMode to prevent popups from opening

### ISSUE THREAD

**Issue by caina-zampieri** [torusresearch/torus-embed#463]
**Is your feature request related to a problem? Please describe.**
In the openlogin options we have the option to set the type of uxMode on login, that would be awesome for the torus

**Describe the solution you'd like**

This code:
uxMode - enum(optional): popup and redirect uxmode are supported. By default it is set to redirect

**Comment by chaitanyapotti** [comment]
We can't do this because torus wallet requires an iframe and the entire login has to happen within the iframe context.
