### ISSUE TITLE
The Top Up section is empty if custom network host is used

### ISSUE THREAD

**Issue by skambalin** [torusresearch/torus-embed#469]
**Describe the bug**
If during the `@toruslabs/torus-embed` initialization a custom network host was provided the `Top Up` section of the wallet application is empty.

**To Reproduce**
1. Initialize `@toruslabs/torus-embed` with custom network host URL
```ts
await this.torusEmbed.init({
  ...
  network: {
    host: 'https://polygon-mumbai.infura.io/v3/...',
    chainId: '...',
  },
});
```
2. Open `Top Up` section in the wallet application
3. The `Top Up` section is empty

**Expected behavior**
The `Top Up` section shows the list of supported providers or an error message that `Top Up` is not supported

**Screenshots**
![TorusTopupSectionBug](https://user-images.githubusercontent.com/56070785/177510835-47905c6b-1816-4a58-b1b0-c95dd50b1365.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser: Google Chrome Version 103.0.5060.53 (Official Build) (x86_64)

**Comment by skambalin** [comment]
It seems to be related to this commit:
https://github.com/torusresearch/torus-website/commit/1b9dfe3424e6e785911c18c4be2d05d1d7fb759b

**Comment by BboyStatix** [comment]
Thanks for describing the issue in detail as well as narrowing down the commit that caused the problem @skambalin. Should be resolved by this PR https://github.com/torusresearch/torus-website/pull/2011
