### ISSUE TITLE
Torus implemented issue in web3-react v8 beta in React

### ISSUE THREAD

**Issue by SChar-Rapid** [torusresearch/torus-embed#495]
When I implented torus-embed in web3-react v8 beta one error is coming from payment provider.But it is only in react not next. The image is given below.
@chaitanyapotti
<img width="480" alt="Screenshot 2022-10-14 at 5 49 58 PM" src="https://user-images.githubusercontent.com/92719513/196169878-6ced58ab-231d-4d16-8fc9-3e5b49fe88f9.png">

**Comment by SashaDesigN** [comment]
Same happens for me on react project...

**Comment by chaitanyapotti** [comment]
Please edit your browserslistconfig to update the supported browsers. ["supports bigint", "not dead"].
If you need more browsers, you need to add latest babel plugins to process 50_000 number syntax
Also, the latest version is only supported in Node 18+
