### ISSUE TITLE
Brave Failed to read the 'sessionStorage' property... Access is denied

### ISSUE THREAD

**Issue by cslarson** [torusresearch/torus-embed#50]
**Describe the bug**
Opening a page with the torus embed on Brave gives the following console error:
> Uncaught DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
>  at onloadTorus (https://app.tor.us/v0.2.3/js/app.c595bc0e.js:1:456475)

Page is served via `http://localhost` (non-ssl) and Brave shields are 'up' (they are up by default on Brave).

**To Reproduce**
1. Page loads, Torus login visible
1. Error is visible in console
1. Click on Torus login, select Reddit, Torus button changes to 'loading' dots
1. See error: `Error during service worker registration: DOMException` in console.

**Expected behavior**
Login should complete or fail with a clearer message about how the user can proceed.

**Screenshots**
![Screenshot from 2019-10-15 10-57-31](https://user-images.githubusercontent.com/900470/66843618-02c3b500-ef3b-11e9-9fac-d27eb7b2bc37.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Brave
 - Version 0.68.131 Chromium: 76.0.3809.100 (Official Build) (64-bit)

**Comment by chaitanyapotti** [comment]
This issue has been fixed and will be released along with v0.2.4 by the end of this month.

Also, when the brave shield is up, google login will not work. This is due to an issue with gapi which tries to set cookies and brave shield disables cross-site cookies
