### ISSUE TITLE
Torus initiateTopup don't accept BRL as selectedCurrency but shows in provider currency list

### ISSUE THREAD

**Issue by diegosano** [torusresearch/torus-embed#548]
**Describe the bug**
Call to method initiateTopup with BRL as selectedCurrency and, for example, mercuryo as the provider,  I got `Error {"selectedCurrency":"Unsupported currency"}` but if I change to USD, in the provider exchange, the currency list has BRL to choose.

**To Reproduce**

1. Call method initiateTopup with mercuryo as provider, and selectedCurrency as BRL (`initiateTopup("mercuryo", { sethe lectedCurrency: "BRL" })`)
2. See error

**Expected behavior**
If the specified payment partner shows the currency, we should be able to use that on selectedCurrency parameter.

**Screenshots**
![Screenshot_23](https://user-images.githubusercontent.com/45228799/222201992-96644fd3-8815-49ee-9ec6-736a25f42416.png)
![image](https://user-images.githubusercontent.com/45228799/222202127-f1a51a17-d9cf-493a-9935-8b619d51c79d.png)
![image](https://user-images.githubusercontent.com/45228799/222202307-aa068759-d4d8-4cfb-b03c-c9db599278c3.png)

**Desktop:**
 - OS: Windows 10
 - Browser Firefox
 - Version 110.0 (64-bits)

**Additional context**
Test realized with next-app example inside torus-embed/examples
https://github.com/torusresearch/torus-embed/tree/develop/examples/next-app

**Comment by chaitanyapotti** [comment]
Fixed in 2.0.1
