### ISSUE TITLE
Error: Unexpected Cache-Control headers, got null

### ISSUE THREAD

**Issue by mikheevm** [torusresearch/torus-embed#55]
**Describe the bug**
When trying to use torus integration within web3connect, following error is thrown when clicking on torus inside the "Choose provider" modal, nothing happens afterwards.

**To Reproduce**
1. Open web3connect modal
2. Click on torus
3. Check the console

**Expected behavior**
Error is not thrown and the integration works

**Screenshots**
<img width="681" alt="Screenshot 2019-11-07 at 15 30 42" src="https://user-images.githubusercontent.com/16622558/68395950-1ead2600-018a-11ea-8c3c-11a0f9a112e9.png">

**Web3Connect provider settings**
```
    torus: {
      package: Torus,
      options: {
        enableLogging: false,
        buttonPosition: 'bottom-left',
        buildEnv: process.env.NODE_ENV,
        showTorusButton: true,
      },
    },
```

```
"@toruslabs/torus-embed": "0.2.6",
```

**Comment by chaitanyapotti** [comment]
It was an issue with our AWS configuration. It's resolved right now. 
If you're still facing the issue, please refresh cache and unregister any service workers present.

**Comment by mikheevm** [comment]
@chaitanyapotti We're still facing this issue, it works only on localhost. You can test/debug it here: https://github.com/gnosis/safe-react/pull/229
