### ISSUE TITLE
Uncaught TypeError: Torus is not a constructor

### ISSUE THREAD

**Issue by binilvjacob** [torusresearch/torus-embed#557]
"https://cdn.jsdelivr.net/npm/@toruslabs/torus-embed"   - > Using this CDN is giving out an error : Uncaught TypeError: Torus is not a constructor. The code was working fine the previous day, but now it is showing this error, and couldn't be used in development

**Comment by xpluscal** [comment]
Second this.

**Comment by chaitanyapotti** [comment]
Pls use `new Torus.default()`
There was a major version release
