### ISSUE TITLE
Error 'torus scripts/package. json' when executing 'npm run build'

### ISSUE THREAD

**Issue by yangyongguan** [torusresearch/torus-embed#565]
**Describe the bug**
When executing 'npm install' and successfully executing 'npm run build', the error 'Error: ENOENT: no such file or directory, open '/C:/Users/yygwo/Desktop/torus-embed/node_modules/@toruslabs/torus-scripts/package.json'' is reported

![image](https://github.com/torusresearch/torus-embed/assets/13481577/c795d730-df16-482d-bc44-27905bad23f0)

**Comment by chaitanyapotti** [comment]
Not sure if npm install succeded. pls check
