### ISSUE TITLE
Torus-Wallet-unpkg

### ISSUE THREAD

**Issue by Tisi22** [torusresearch/torus-embed#566]
**Describe the bug**
The unpkg example that you have in your website does not work

**To Reproduce**
1. Go to '[Torus](https://docs.tor.us/integration-builder/?b=wallet&chain=Ethereum&lang=HTML)'
2. Click on 'unpkg'
3. Copy code and follow instructions
4. See error: Torus is not a constructur

**Comment by binilvjacob** [comment]
I am also facing the same issue. Is there a fix for this ?
