### ISSUE TITLE
Copy Writing and Formation of Elements within the Window

### ISSUE THREAD

**Issue by elishatorus** [torusresearch/torus-embed#68]
<img width="321" alt="Screenshot 2019-12-17 at 11 52 38 AM" src="https://user-images.githubusercontent.com/51352241/70963772-75c8e380-20c4-11ea-855b-1cc5bba4b768.png">

The elements and padding of the buttons should be properly aligned.

Copywriting:
Action Required
You have a pending action that needs to be completed in a pop-up window. Please click the button to proceed.

**Comment by chaitanyapotti** [comment]
Fixed
