### ISSUE TITLE
Use specific CSS classes

### ISSUE THREAD

**Issue by elishatorus** [torusresearch/torus-embed#78]
**Describe the bug**
The login screen does not look right.

**To Reproduce**
1. Inject Torus script to https://lottoshi.io/en/home
2. Go to the site (https://lottoshi.io/en/home)
3. Attempt to login, with the Torus login button.

**Expected behavior**
The login screen should be proper and polished.

**Screenshots**
<img width="1679" alt="Screenshot 2020-01-02 at 2 51 41 PM" src="https://user-images.githubusercontent.com/51352241/71654955-7e314780-2d6f-11ea-91ae-d6bc88b84d40.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Comment by chaitanyapotti** [comment]
Fixed
