### ISSUE TITLE
Warning from random-id is causing CI to fail

### ISSUE THREAD

**Issue by TomAFrench** [torusresearch/torus-embed#91]
**Describe the bug**

Due to the way that [random-id](https://github.com/KingCosmic/random-id) is exporting its function, a warning is emitted during build while using Torus. Travis treats all warnings as errors so this causes all builds to fail.

**Expected behavior**

Zero warnings when building.

**Link**

https://github.com/wearekickback/app/pull/280

**Comment by chaitanyapotti** [comment]
We created a patch version of his package.
we'll be using the patched version until the maintainer updates his package.

This bug is fixed and will be released in the next version (v0.2.14) before Feb 7 2020.

**Comment by KingCosmic** [comment]
if you'd like to share your patch for the issue I'd love to update my package with it, I'm having issues getting your package to run for me to find a suitable solution. @chaitanyapotti

**Comment by chaitanyapotti** [comment]
Here is the repo: https://github.com/chaitanyapotti/random-id
npm package: https://www.npmjs.com/package/@chaitanyapotti/random-id
